### ISSUE TITLE
title screen presence

### ISSUE THREAD

**Issue by Lunaversitay** [Tenrys/gmod_discordrpc#3]
needs crident networks if they're not in a server, so they can know where to get a server

btw when does this get mysql support

**Comment by Tenrys** [comment]
nice meme, but can't touch menu lua

mysql support for what

**Comment by Lunaversitay** [comment]
i mean if they're not in a server it shows up crident networks on their presence becuz they need a server

mysql support for the addon obviously

**Comment by Tenrys** [comment]
bad meme
