### ISSUE TITLE
Tabbing out

### ISSUE THREAD

**Issue by Stanstar22** [Tenrys/gmod_discordrpc#4]
Tabbing out for long enough causes for it all to disappear and say you're just playing Garry's Mod and not come back unless you reconnect.

**Comment by Tenrys** [comment]
Nothing I can really do about, really, unless we get a way to get the game's process ID.

**Comment by Tenrys** [comment]
https://github.com/discordapp/discord-rpc/issues/191#issuecomment-395171099
