### ISSUE TITLE
Stuck on Initializing

### ISSUE THREAD

**Issue by TinkleTingler** [Tenrys/gmod_discordrpc#5]
https://gyazo.com/26c25a74020e26cd9b65ab43dbf5209b

Here is the console to my server. 

`[Discord RPC] HTTP loaded, trying to init
[Discord RPC] Finding port
[Discord RPC] Connection success on port 6463! 
[Discord RPC] First SetActivity test was successful, ready to work!
[Discord RPC] Loading states:
	Loaded: discordrpc/states/default.lua
	Loaded: discordrpc/states/example.lua
`

I believe I followed the instructions as is. The only thing I can think of being a problem is the fact I renamed darkrp gamemode to civilwar.

**Comment by Tenrys** [comment]
I've also noticed this problem on my own. Basically you can only set the presence once and that's it, I'm not quite sure why that is. I think Discord might have broken something, I'll try asking them.

**Comment by CubitsDev** [comment]
Same issue with myself, and what seems like the library MonolithRP use. Seems Discord Changed some stuff

**Comment by Tenrys** [comment]
I looked a little bit at the docs and nothing seems to have changed, weird.

**Comment by Tenrys** [comment]
https://github.com/discordapp/discord-rpc/issues/191#issuecomment-395171099
